[기능] 점주 음식 상품 게시
woowa-techcamp-2024/Team1-3K1K pull request #51
Opened 2024-08-14 10:59 UTC by june-777

## 💡 다음 이슈를 해결했어요.
### Issue Link - #8 

<br>

## 💡 이런 고민을 했어요.
### 가게, 메뉴, 메뉴카테고리 엔티티 설계
<img width="450" alt="image" src="https://github.com/user-attachments/assets/d4604041-9a6c-43d9-a124-20a7aaa77f93">

1. 음식 상품 카테고리가 가게를 참조하고 있어야하는지 고민. 결론적으로는 참조하고 있어야 함

- 기능 요구사항: 음식 상품에서 카테고리를 기재할 때, 해당 가게에 등록한 음식 카테고리를 조회한다.

- 위의 요구사항을 만족하기 위해선, 가게ID를 기준으로 음식 상품 카테고리를 조회할 수 있어야 함. 음식 상품 카테고리가 가게를 참조 (FK)하고 있지 않는다면, 가게 ID 기준으로 음식 카테고리를 조회하는데 제약이 있음.

2. 연관관계 매핑에 대한 고민. 결론적으로는 음식 상품 카테고리 - 가게를 다대일로 설계

- 음식 상품 카테고리는 메인 메뉴, 사이드 메뉴, 해산물 메뉴, 식사 메뉴, 점심 메뉴 즉, 해당 가게 점주가 원하는 카테고리를 커스텀하게 등록할 수 있다. 다시말해, 음식 상품 카테고리는 특정 가게에 종속된다.
- 음식 상품 카테고리는 하나의 가게에 종속된다. 하나의 가게는 여러 음식 상품 카테고리를 가질 수 있다.

<br>

## ✅ 셀프 체크리스트
- [x] 내 코드를 스스로 검토했습니다.
- [x] 필요한 테스트를 추가했습니다.
- [x] 모든 테스트를 통과합니다.
- [x] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있습니다.
- [x] 커밋 메세지를 컨벤션에 맞추었습니다.
- [ ] wiki를 수정했습니다.

2024-08-14 12:53 UTC, Hyeon-Uk commented on src/main/java/camp/woowak/lab/store/service/StoreMenuRegistrationService.java
> +	public void storeMenuRegistration(final Vendor owner, final StoreMenuRegistrationRequest request) {
Vendor : Store = 1 : N 관계인데 ownerId를 이용해서 단일 Store를 return 받으면 항상 첫번째로 등록된 Store만 return되지 않을까요?

메뉴를 등록하고 싶은 Store의 Id도 함께 받아 쿼리를 날려야한다고 생각합니다!

2024-08-14 13:25 UTC, Dr-KoKo commented on src/main/java/camp/woowak/lab/store/repository/StoreRepository.java
> +	Optional<Store> findByOwnerId(Long ownerId);
여기도 List로 반환될 거 같아요

2024-08-14 14:27 UTC, june-777 commented on src/main/java/camp/woowak/lab/store/service/StoreMenuRegistrationService.java
> +	public void storeMenuRegistration(final Vendor owner, final StoreMenuRegistrationRequest request) {
앗.. 그러네요 다시 반영해두겠습니다. 꼼꼼한 리뷰 감사합니다 👍

2024-08-14 14:28 UTC, june-777 commented on src/main/java/camp/woowak/lab/store/repository/StoreRepository.java
> +	Optional<Store> findByOwnerId(Long ownerId);
그러네요 ㅎㅎ.. 수정해서 반영해두겠습니다!

2024-08-14 15:17 UTC, june-777 commented on src/main/java/camp/woowak/lab/store/service/StoreMenuRegistrationService.java
> +	public void storeMenuRegistration(final Vendor owner, final StoreMenuRegistrationRequest request) {
가게 ID를 기준으로 조회하도록 수정하였습니다. [a8fc0a8](https://github.com/woowa-techcamp-2024/Team1-3K1K/pull/51/commits/a8fc0a8b23f66f5b16032e6c991a33193049b381)

2024-08-14 15:17 UTC, june-777 commented on src/main/java/camp/woowak/lab/store/repository/StoreRepository.java
> +	Optional<Store> findByOwnerId(Long ownerId);
가게 ID를 기준으로 조회하도록 수정하였습니다. [a8fc0a8](https://github.com/woowa-techcamp-2024/Team1-3K1K/pull/51/commits/a8fc0a8b23f66f5b16032e6c991a33193049b381)

2024-08-14 15:24 UTC, Hyeon-Uk commented on src/main/java/camp/woowak/lab/store/service/StoreMenuRegistrationService.java
> +	public void storeMenuRegistration(final Vendor owner, final StoreMenuRegistrationRequest request) {
LGTM! :-)

2024-08-14 15:24 UTC, Hyeon-Uk approved these changes
LGTM :-)

2024-08-14 15:56 UTC, Hyeon-Uk requested changes

2024-08-14 15:56 UTC, Hyeon-Uk commented on src/main/java/camp/woowak/lab/menu/domain/Menu.java
메뉴 도메인 엔티티에 메뉴의 수량에 대한 컬럼이 존재하지 않습니다!

2024-08-15 00:21 UTC, Dr-KoKo commented on src/main/java/camp/woowak/lab/menu/domain/Menu.java
초반에 기능단위로 일감을 분배하다보니 이슈 하나에서 너무 많은 작업이 발생하는 것 같습니다.
`점주 음식 상품 게시`는 사실 1.`점주의 메뉴 카테고리 등록`+2.`점주의 메뉴 등록`+3.`점주의 수량 등록 및 게시`가 모두 포함되어 있는 기능이기 때문에 좀 더 잘게 쪼갤 필요가 있는 것 같아요.
`점주의 메뉴 카테고리 등록`은 이미 별도의 backlog로 생성되어 있기 때문에  **`점주의 수량 등록 및 게시`를 새로운 이슈**로 만들어서 작업해주시면 될 것 같습니다.

2024-08-15 02:18 UTC, june-777 commented on src/main/java/camp/woowak/lab/menu/domain/Menu.java
네네 말씀하신대로 더 잘게 쪼개면서 진행하면 수월할듯 합니다.
approve 완료되면, merge부터 먼저 진행하겠습니다.

2024-08-15 02:25 UTC, Dr-KoKo approved these changes
음식 메뉴에 대한 수량 및 판매 게시는 #59 에서 처리합니다.

2024-08-15 02:30 UTC, Hyeon-Uk approved these changes

2024-08-15 02:31 UTC, merged