[feat] 음식 상품 수량 등록
woowa-techcamp-2024/Team1-3K1K pull request #76
Opened 2024-08-15 11:15 UTC by june-777

## 💡 다음 이슈를 해결했어요.

### Issue Link - #59 
- 비즈니스 요구사항을 최소화하기 위해, 음식 상품 수량은 점주가 음식 상품을 등록할 때 **함께 등록**합니다.
- 따라서 별도의 API는 생성하지 않았으며, 음식 상품(Menu)의 인스턴스 필드와 생성자에 재고수(stockCount)를 추가하였습니다.

<br>

## ✅ 셀프 체크리스트

- [x] 내 코드를 스스로 검토했습니다.
- [x] 필요한 테스트를 추가했습니다.
- [x] 모든 테스트를 통과합니다.
- [x] 브랜치 전략에 맞는 브랜치에 PR을 올리고 있습니다.
- [x] 커밋 메세지를 컨벤션에 맞추었습니다.
- [ ] wiki를 수정했습니다.

2024-08-15 11:29 UTC, Dr-KoKo reviewed
1)메뉴를 등록할 때 재고 개수를 같이 입력한다.
2-1) 재고가 남아있으면 주문이 성공한다.
2-2) 재고가 소진되면 주문이 실패한다.
의 동작을 생각하고 계신걸까요?

점주에게 알림을 띄우지 않아도 되기 때문에 프로젝트 사이즈가 확실히 줄겠다고 생각하는데 다른 분들 의견도 한번 들어보는게 좋을 것 같아요.
@Hyeon-Uk @kimhyun5u

2024-08-15 11:39 UTC, june-777 commented
@Dr-KoKo 
음식 상품 등록할 때, 수량도 함께 입력하여 음식 상품을 등록하도록 한 것입니다. (Create, Update 중 Create만)
기존의 요구사항에서 크게 변동되는 부분은 없는 것 같은데, 아래의 이야기는 어떤 말씀이실까요??

> 점주에게 알림을 띄우지 않아도 되기 때문에

2024-08-15 11:52 UTC, Dr-KoKo commented
> @Dr-KoKo 점주가 음식 상품 등록할 때, 수량도 함께 입력하여 음식 상품을 등록하도록 한 것입니다. (Create, Update 중 Create만) 기존의 요구사항에서 크게 변동되는 부분은 없는 것 같은데, 아래의 이야기는 어떤 말씀이실까요??
> 
> > 점주에게 알림을 띄우지 않아도 되기 때문에

재고를 추가로 등록하는게 아니라 Menu 생성시점에 재고를 바로 입력받자는 말씀이신가보네요.

>"비즈니스 요구사항을 최소화하기 위해, 음식 상품 수량은 점주가 음식 상품을 등록할 때 함께 등록합니다."

저는 점주가 재고를 갱신하는 기능을 생각했는데 "점주가 음식 상품을 등록할 때 함께 등록합니다"로 결정하시게 된 배경이 궁금합니다.

2024-08-15 11:56 UTC, june-777 commented
네네 맞습니다.

첫 번째 이유는 PR 단위를 짧게 가져가기 위함이였고,
두 번쨰 이유는 현재 정의된 백로그들이 아직 많은 상황이라 CRUD에서 U,D는 우선순위가 낮다고 판단했습니다.
따라서 추후에 필요시에 구현해도 될 것이라 생각했습니다 :)

2024-08-15 12:01 UTC, Dr-KoKo commented
> 네네 맞습니다.
> 
> 첫 번째 이유는 PR 단위를 짧게 가져가기 위함이였고, 두 번쨰 이유는 현재 정의된 백로그들이 아직 많은 상황이라 CRUD에서 U,D는 우선순위가 낮다고 판단했습니다. 따라서 추후에 필요시에 구현해도 될 것이라 생각했습니다 :)

아하 알겠습니다. 금일 10시에 회의하면서 어디까지 쳐낼지 논의해보면 좋을 것 같네요. 알림기능을 완전히 쳐내는 것도 한 방안일 것 같아서 말씀드려봤습니다!

2024-08-15 12:08 UTC, june-777 commented
> 아하 알겠습니다. 금일 10시에 회의하면서 어디까지 쳐낼지 논의해보면 좋을 것 같네요. 알림기능을 완전히 쳐내는 것도 한 방안일 것 같아서 말씀드려봤습니다!

좋습니다!

2024-08-15 12:37 UTC, Hyeon-Uk requested changes

2024-08-15 12:37 UTC, Hyeon-Uk commented on src/test/java/camp/woowak/lab/menu/domain/MenuTest.java
`InvalidMenuCreationException` 은 각각의 필드별로 ErrorCode가 다른것을 볼 수 있는데, 테스트코드에서 그 ErrorCode 또한 검증해주면 좋을 것 같습니다!

2024-08-15 14:42 UTC, Dr-KoKo approved these changes
금일 논의를 거쳐 (점주의 승락/거절 절차 없이) 재고가 있으면 자동승락, 없으면 자동거절되게 요구사항이 변경되었습니다.

2024-08-16 02:03 UTC, june-777 commented on src/test/java/camp/woowak/lab/menu/domain/MenuTest.java
ErrorCode로 세부적으로 검증하도록 수정했습니다 :)
[c9fd590](https://github.com/woowa-techcamp-2024/Team1-3K1K/pull/76/commits/c9fd590fbf6dda88d94a7504ae75dfa1bf9f6e00)

2024-08-16 02:05 UTC, Hyeon-Uk approved these changes
테스트 빨리 고치시길 기원하겠습니다 :-) 🙏

2024-08-16 02:07 UTC, june-777 commented
> 테스트 빨리 고치시길 기원하겠습니다 :-) 🙏

[754e122](https://github.com/woowa-techcamp-2024/Team1-3K1K/pull/76/commits/754e12227fe1fe62a88cdcb451bc9806db4bdaad) fix 완료했습니다 🙏

2024-08-16 02:07 UTC, merged